artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/download?id=184K8sLVcL_fq76pA2o8Bg4BthNLcwUel&export=download&authuser=0&confirm=t
  local_data_file: artifacts/data_ingestion/labels_and_dataset.zip

data_validation:
  root_dir: artifacts/data_validation
  dataset_folder: artifacts/data_ingestion/dataset
  dataset_labels: artifacts/data_ingestion/labels.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_folder: artifacts/data_ingestion/dataset
  transformed_dataset: artifacts/data_transformation/dataset
  dataset_labels_src: artifacts/data_ingestion/labels.csv
  dataset_labels: artifacts/data_transformation/labels.csv
